// SURGITOME — (c) 2026 Piotr Spychalski, MD, PhD, Medical University of Gdańsk · piotr.spychalski@gumed.edu.pl · ORCID 0000-0001-7111-4660 · MIT License
const {JSDOM}=require('jsdom'); const fs=require('fs');
const html=fs.readFileSync(require('path').join(__dirname,'../dist/surgitome.html'),'utf8').replace(/<script src[^>]*><\/script>/g,'');
const dom=new JSDOM(html,{runScripts:'outside-only',pretendToBeVisual:true,url:'https://x.test/'}); Object.defineProperty(dom.window.navigator,'languages',{value:['pl-PL']}); Object.defineProperty(dom.window.navigator,'language',{value:'pl-PL'});  dom.window.localStorage.setItem('surgitome-intro','1'); dom.window.localStorage.setItem('surgitome-tour','1'); /* informacja startowa już potwierdzona */ if(process.argv[2]==='stored') dom.window.localStorage.setItem('surgitome-fav',JSON.stringify(['ladd','ipaa'])); const w=dom.window;
w.matchMedia=()=>({matches:false,addEventListener(){}});
w.HTMLCanvasElement.prototype.getContext=function(){return new Proxy({},{get(_,k){ if(k==='createImageData') return (a,b)=>({data:new Uint8ClampedArray(a*b*4)}); if(k==='measureText') return ()=>({width:10}); return ()=>null; }, set(){return true}})};
const T=Object.assign({},require('three'));
T.WebGLRenderer=function(){return {clearDepth(){},setPixelRatio(){},setSize(){},capabilities:{getMaxAnisotropy:()=>8},setScissorTest(){},setViewport(){},setClearColor(){},clear(){},render(){},setScissor(){},getPixelRatio:()=>1}};
w.THREE=T; w.eval(fs.readFileSync(require('path').join(require('path').dirname(require.resolve('three')),'../examples/js/controls/OrbitControls.js'),'utf8'));
const errs=[]; w.addEventListener('error',e=>errs.push(e.message||String(e.error)));
const sc=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]); w.eval(sc[0]); w.eval(sc[1]);
const $=id=>w.document.getElementById(id); const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const tabs=()=>[...$('tabs').querySelectorAll('.tab')].map(b=>b.firstChild.textContent+(b.querySelector('.star.on')?'★':'☆')+(b.getAttribute('aria-selected')==='true'?'*':''));
(async()=>{ await sleep(400);
  const steps=[...w.document.querySelectorAll('.srow1 .step')]; steps[steps.length-1].click(); await sleep(700);
  const key=k=>w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:k,bubbles:true}));
  console.log('kadr:',$('capTitle').textContent,'| przycisk:',$('ctSweep').textContent);
  key('ArrowRight'); await sleep(300); console.log('po 1. „Dalej”: przycisk',$('ctSweep').textContent,'| kadr:',$('capTitle').textContent);
  key('PageDown'); await sleep(700); console.log('po 2. „Dalej” (pilot):',$('capTitle').textContent,'|',$('pTitle').textContent);
  console.log(errs.length?errs:'errors []'); process.exit(0);
})();
